# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13431cdca553176032ec3733b12d4780f39aa9cfe1d7aa439765505060023f3e73339d7b0a4e2dec9b06cf8cc3692f27b7608abe282eb8b63af636e874ba8723

test:
  secret_key_base: 490eb7025f33ee0ecbc5e36c71fa5692e8bcd553482975368e743f068b359ccf4d81f421db76d9b2b9734b48ea945811c441c6eae55ba251c4beec0b9ee09ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
